version: '3.8'

services:
  app:
    container_name: cloak-service
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    container_name: cloak-redis
    image: redis:alpine
